# 服务端口
port:
  - 8080
  - 9090
# 版本号
version: 1.0.0
# 随机最大的网络延时，用于模拟通讯延时。单位 毫秒
maxdelay: 10
# 预定义的类型
types:
  - {name: String,label: 字符串,length: ,option: ,validator: }
  - {name: Date,label: 日期 ,length: 10,option: "[1-9]\\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])" ,validator: regex}
  - {name: Time,label: 时间 ,length: 8,option: "(20|21|22|23|[0-1]\\d):[0-5]\\d:[0-5]\\d" ,validator: regex}
  - {name: DateTime,label: 日期时间 ,length: 19,option: "[1-9]\\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])\\s+(20|21|22|23|[0-1]\\d):[0-5]\\d:[0-5]\\d" ,validator: regex}
  - {name: Dict,label: 字典类型,length: ,option: ,validator: dict }
  - {name: Numric,label: 数字字符串,length: ,option: "[0-9]\\d*" ,validator: regex }
  - {name: Sex,label: 字典类型,length: ,option: sex ,validator: dict }
  - {name: Int,label: 整型 ,length: 10, option: "[-]?[0-9]\\d+", validator: regex}
  - {name: Bool,label: 布尔类型,length:5 ,option: bool ,validator: dict }
# 预定义的字典类型
dict:
  - code: sex
    values:
      - {key: 1,label: 男}
      - {key: 2,label: 女}
  - code: bool
    values:
      - {key: true,label: 真}
      - {key: false,label: 假}