# 服务端口
port:
  - 8080
  - 9090
# 版本号
version: 1.0.0
# 预定义的类型
types:
  - {name: String,label: 字符串,length: ,option: ,validator: }
  - {name: Date,label: 日期 ,length: 8,option: "[1-9]\\d*" ,validator: regex}